"""add created_at token expire

Revision ID: 7dd0698262b4
Revises: 9b1c2ebd7d2c
Create Date: 2023-01-01 22:21:57.720359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd0698262b4'
down_revision = '9b1c2ebd7d2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
